/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author khushbu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionTabs = new javax.swing.JTabbedPane();
        tabPersonalInfo = new javax.swing.JPanel();
        tabAddress = new javax.swing.JPanel();
        tabBankInformation = new javax.swing.JPanel();
        tabLicense = new javax.swing.JPanel();
        tabMedical = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actionTabs.setBackground(new java.awt.Color(255, 255, 255));
        actionTabs.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        javax.swing.GroupLayout tabPersonalInfoLayout = new javax.swing.GroupLayout(tabPersonalInfo);
        tabPersonalInfo.setLayout(tabPersonalInfoLayout);
        tabPersonalInfoLayout.setHorizontalGroup(
            tabPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        tabPersonalInfoLayout.setVerticalGroup(
            tabPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        actionTabs.addTab("Personal", tabPersonalInfo);

        javax.swing.GroupLayout tabAddressLayout = new javax.swing.GroupLayout(tabAddress);
        tabAddress.setLayout(tabAddressLayout);
        tabAddressLayout.setHorizontalGroup(
            tabAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        tabAddressLayout.setVerticalGroup(
            tabAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        actionTabs.addTab("Address", tabAddress);

        javax.swing.GroupLayout tabBankInformationLayout = new javax.swing.GroupLayout(tabBankInformation);
        tabBankInformation.setLayout(tabBankInformationLayout);
        tabBankInformationLayout.setHorizontalGroup(
            tabBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        tabBankInformationLayout.setVerticalGroup(
            tabBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        actionTabs.addTab("Bank", tabBankInformation);

        javax.swing.GroupLayout tabLicenseLayout = new javax.swing.GroupLayout(tabLicense);
        tabLicense.setLayout(tabLicenseLayout);
        tabLicenseLayout.setHorizontalGroup(
            tabLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        tabLicenseLayout.setVerticalGroup(
            tabLicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        actionTabs.addTab("License", tabLicense);

        javax.swing.GroupLayout tabMedicalLayout = new javax.swing.GroupLayout(tabMedical);
        tabMedical.setLayout(tabMedicalLayout);
        tabMedicalLayout.setHorizontalGroup(
            tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        tabMedicalLayout.setVerticalGroup(
            tabMedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        actionTabs.addTab("Medical", tabMedical);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane actionTabs;
    private javax.swing.JPanel tabAddress;
    private javax.swing.JPanel tabBankInformation;
    private javax.swing.JPanel tabLicense;
    private javax.swing.JPanel tabMedical;
    private javax.swing.JPanel tabPersonalInfo;
    // End of variables declaration//GEN-END:variables
}
