/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person;

/**
 *
 * @author khushbu
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    
    Person person;
    
    public ReportJPanel(Person person) {
        initComponents();
        this.person = person;
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panePersonalInfo = new javax.swing.JPanel();
        lblTitlePersonalInfo = new javax.swing.JLabel();
        jPaneFirstName = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JLabel();

        panePersonalInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitlePersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersonalInfo.setLabelFor(panePersonalInfo);
        lblTitlePersonalInfo.setText("Personal Information");
        lblTitlePersonalInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitlePersonalInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblFirstName.setText("First Name : ");

        javax.swing.GroupLayout jPaneFirstNameLayout = new javax.swing.GroupLayout(jPaneFirstName);
        jPaneFirstName.setLayout(jPaneFirstNameLayout);
        jPaneFirstNameLayout.setHorizontalGroup(
            jPaneFirstNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneFirstNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFirstName)
                .addGap(18, 18, 18)
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneFirstNameLayout.setVerticalGroup(
            jPaneFirstNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneFirstNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneFirstNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName))
                .addContainerGap())
        );

        javax.swing.GroupLayout panePersonalInfoLayout = new javax.swing.GroupLayout(panePersonalInfo);
        panePersonalInfo.setLayout(panePersonalInfoLayout);
        panePersonalInfoLayout.setHorizontalGroup(
            panePersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panePersonalInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPaneFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panePersonalInfoLayout.setVerticalGroup(
            panePersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePersonalInfoLayout.createSequentialGroup()
                .addComponent(lblTitlePersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPaneFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panePersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panePersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPaneFirstName;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblTitlePersonalInfo;
    private javax.swing.JPanel panePersonalInfo;
    private javax.swing.JLabel txtFirstName;
    // End of variables declaration//GEN-END:variables

    private void displayData() {
       txtFirstName.setText(person.getFirstName()); 
    }
}
