/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author khushbu
 */
public class ViewSavingBankInfo extends javax.swing.JPanel {

    Person person;
    
    /**
     * Creates new form PersonalInformationPanel
     */
    public ViewSavingBankInfo(Person person) {
        initComponents();
        this.person = person;
        displayData();
    }
    
//     private String pattern = "dd-MMM-yyyy";
//     private SimpleDateFormat dateFormat = new SimpleDateFormat(pattern);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateComponentFormatter1 = new org.jdatepicker.DateComponentFormatter();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tabBodyBankInformation = new javax.swing.JPanel();
        lblSavingBankRoutingNo = new javax.swing.JLabel();
        lblSavingBankAccNo = new javax.swing.JLabel();
        txtSavingsBankRoutingNo = new javax.swing.JTextField();
        checkBoxSavings = new javax.swing.JCheckBox();
        titleChecking = new javax.swing.JLabel();
        txtSavingsBankName = new javax.swing.JTextField();
        lblSavingBankName = new javax.swing.JLabel();
        lblSavingBankAccBalance = new javax.swing.JLabel();
        txtSavingsAccBalance = new javax.swing.JTextField();
        txtSavingsBankAccNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(249, 244, 244));

        tabBodyBankInformation.setBackground(new java.awt.Color(249, 244, 244));

        lblSavingBankRoutingNo.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSavingBankRoutingNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSavingBankRoutingNo.setText("Bank Routing Number");

        lblSavingBankAccNo.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSavingBankAccNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSavingBankAccNo.setText("Bank Account Number");

        txtSavingsBankRoutingNo.setEditable(false);
        txtSavingsBankRoutingNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        txtSavingsBankRoutingNo.setFocusTraversalKeysEnabled(false);
        txtSavingsBankRoutingNo.setFocusable(false);
        txtSavingsBankRoutingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavingsBankRoutingNoActionPerformed(evt);
            }
        });

        checkBoxSavings.setBackground(new java.awt.Color(249, 244, 244));
        checkBoxSavings.setSelected(true);
        checkBoxSavings.setText("Saving Bank Account");
        checkBoxSavings.setEnabled(false);
        checkBoxSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSavingsActionPerformed(evt);
            }
        });

        titleChecking.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        titleChecking.setText("View Saving Account Details");

        txtSavingsBankName.setEditable(false);
        txtSavingsBankName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        txtSavingsBankName.setFocusTraversalKeysEnabled(false);
        txtSavingsBankName.setFocusable(false);
        txtSavingsBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavingsBankNameActionPerformed(evt);
            }
        });

        lblSavingBankName.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSavingBankName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSavingBankName.setText("Bank Name");

        lblSavingBankAccBalance.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSavingBankAccBalance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSavingBankAccBalance.setText("Account Balance");

        txtSavingsAccBalance.setEditable(false);
        txtSavingsAccBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        txtSavingsAccBalance.setFocusTraversalKeysEnabled(false);
        txtSavingsAccBalance.setFocusable(false);
        txtSavingsAccBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavingsAccBalanceActionPerformed(evt);
            }
        });

        txtSavingsBankAccNo.setEditable(false);
        txtSavingsBankAccNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        txtSavingsBankAccNo.setFocusTraversalKeysEnabled(false);
        txtSavingsBankAccNo.setFocusable(false);
        txtSavingsBankAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavingsBankAccNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabBodyBankInformationLayout = new javax.swing.GroupLayout(tabBodyBankInformation);
        tabBodyBankInformation.setLayout(tabBodyBankInformationLayout);
        tabBodyBankInformationLayout.setHorizontalGroup(
            tabBodyBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBodyBankInformationLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(tabBodyBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSavingsBankRoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavingsBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavingBankRoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavingBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleChecking)
                    .addComponent(txtSavingsAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavingsBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavingBankAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavingBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        tabBodyBankInformationLayout.setVerticalGroup(
            tabBodyBankInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBodyBankInformationLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleChecking)
                .addGap(30, 30, 30)
                .addComponent(lblSavingBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSavingsBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblSavingBankRoutingNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSavingsBankRoutingNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblSavingBankAccNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSavingsBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblSavingBankAccBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSavingsAccBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(checkBoxSavings)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabBodyBankInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tabBodyBankInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSavingsBankRoutingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavingsBankRoutingNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavingsBankRoutingNoActionPerformed

    private void checkBoxSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSavingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxSavingsActionPerformed

    private void txtSavingsBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavingsBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavingsBankNameActionPerformed

    private void txtSavingsAccBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavingsAccBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavingsAccBalanceActionPerformed

    private void txtSavingsBankAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavingsBankAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavingsBankAccNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxSavings;
    private org.jdatepicker.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.JLabel lblSavingBankAccBalance;
    private javax.swing.JLabel lblSavingBankAccNo;
    private javax.swing.JLabel lblSavingBankName;
    private javax.swing.JLabel lblSavingBankRoutingNo;
    private javax.swing.JPanel tabBodyBankInformation;
    private javax.swing.JLabel titleChecking;
    private javax.swing.JTextField txtSavingsAccBalance;
    private javax.swing.JTextField txtSavingsBankAccNo;
    private javax.swing.JTextField txtSavingsBankName;
    private javax.swing.JTextField txtSavingsBankRoutingNo;
    // End of variables declaration//GEN-END:variables

    private void displayData() {
            txtSavingsBankName.setText(person.getSavingBankName());
            txtSavingsBankRoutingNo.setText(person.getSavingBankRoutingNumber());
            txtSavingsBankAccNo.setText(person.getSavingBankAccountNumber());
            txtSavingsAccBalance.setText(person.getSavingAccountBalance());
            checkBoxSavings.setSelected(person.isIsSavingAccountType());
        }
}

