/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khushbu
 */
public class SelectRestaurantPanel extends javax.swing.JPanel {

    JPanel mainPanel;
    EcoSystem ecosystem;
    UserAccount userAccount;

    /**
     * Creates new form SelectRestaurantPanel
     *
     * @param mainPanel
     * @param ecosystem
     * @param userAccount
     */
    
    public SelectRestaurantPanel(JPanel mainPanel, EcoSystem ecosystem, UserAccount userAccount) {
        this.mainPanel = mainPanel;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        initComponents();
        populateRestaurants();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChooseRestaurant = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantList = new javax.swing.JTable();

        setBackground(new java.awt.Color(237, 255, 236));

        btnChooseRestaurant.setBackground(new java.awt.Color(255, 255, 255));
        btnChooseRestaurant.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnChooseRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        btnChooseRestaurant.setText("Choose & Continue");
        btnChooseRestaurant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        btnChooseRestaurant.setBorderPainted(false);
        btnChooseRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseRestaurantActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText(" Select Restaurant to place order");

        tblRestaurantList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tblRestaurantList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sr No.", "Name", "Phone number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRestaurantList.setSelectionBackground(new java.awt.Color(0, 102, 204));
        jScrollPane1.setViewportView(tblRestaurantList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(btnChooseRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnChooseRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseRestaurantActionPerformed
        Restaurant r = getSelectedRestaurant();

        if (r != null) {
            ManageCartPanel manageCart = new ManageCartPanel(mainPanel, ecosystem, userAccount, r);
            mainPanel.add("ManageCartPanel", manageCart);

            CardLayout layout = (CardLayout) mainPanel.getLayout();
            layout.next(mainPanel);
        }
    }//GEN-LAST:event_btnChooseRestaurantActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseRestaurant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblRestaurantList;
    // End of variables declaration//GEN-END:variables

    private Restaurant getSelectedRestaurant() {
        int selectedRowIndex = tblRestaurantList.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Oops! Please select a restaurant first.");
            return null;
        }

        Restaurant r = (Restaurant) tblRestaurantList.getValueAt(selectedRowIndex, 1);

        return r;
    }

    private void populateRestaurants() {
        RestaurantDirectory restaurantDirectory = ecosystem.getRestaurantDirectory();

        DefaultTableModel model = (DefaultTableModel) tblRestaurantList.getModel();

        int count = 1;

        model.setRowCount(0);
        for (Restaurant restaurant : restaurantDirectory.getRestaurantList()) {
            Object[] row = new Object[6];
            row[0] = "" + count++;
            row[1] = restaurant;
            row[2] = restaurant.getPhone();
            row[3] = restaurant.getAddress();

            model.addRow(row);
        }
    }
}
